### ISSUE TITLE
Liscence key is invalid

### ISSUE THREAD

**Issue by SoapyRonjon** [Kaizen2977/Burp-Loader-Windows#1]
when I put in the generated key from Keygen.jar into the burpsuite jar is had the error "The supplied liscence key was not recognised, please try re-entering your liscence key."
![Screenshot 2024-08-29 201844](https://github.com/user-attachments/assets/d9beada0-abfc-4994-810d-c840891cc9e2)

**Comment by Kaizen2977** [comment]
don't change the name in keygen or sometimes keygen is not working properly in some system so you can wait and try after some time.
